### ISSUE TITLE
There is a long way to go for joinery!

### ISSUE THREAD

**Issue by axhiao** [cardillo/joinery#52]
Joinery misses too many useful api. For example, I cannot even set a specific type for fields from .csv file in the method of `read_csv` method. Joinery just reads original `String` type as `Double` and I just can do nothing about this.

**Comment by cardillo** [comment]
Can you give me an example of what you are trying to do?

**Comment by axhiao** [comment]
I am trying to specify the type of fields when invoking `read_csv`. For example, when getting a data of field, `12346789`, Joinery parses the data into long type whereas I want a string  type.

**Comment by cardillo** [comment]
By default, `readCsv` tries to infer the correct data type for each column.  If this inference is incorrect or not desired, I suggest using `convert` to ensure columns are marked with the correct type.  `readXls` may also be of use, since workbooks can contain additional information about the column types.

**Comment by axhiao** [comment]
Thank you!
